"""Pydantic data model shared by every agent (the inter-agent contract)."""

from catia_diff.models.drawing import (
    Annotation,
    DatumFeature,
    DatumRef,
    Dimension,
    DimensionKind,
    DrawingDocument,
    GDTCharacteristic,
    GeometricTolerance,
    GeometryFeature,
    GeometryKind,
    MaterialCondition,
    ProjectionMethod,
    Sheet,
    SourceFormat,
    SurfaceFinish,
    TitleBlock,
    TitleBlockField,
    Tolerance,
    ToleranceKind,
    Units,
    View,
    WeldSymbol,
)
from catia_diff.models.findings import (
    AuditReport,
    Category,
    Evidence,
    Finding,
    Severity,
)
from catia_diff.models.geometry import BBox, CoordinateSpace, Point2D
from catia_diff.models.messages import AgentResult, AgentStatus, AgentTask, TaskKind

__all__ = [
    "Annotation",
    "AgentResult",
    "AgentStatus",
    "AgentTask",
    "AuditReport",
    "BBox",
    "Category",
    "CoordinateSpace",
    "DatumFeature",
    "DatumRef",
    "Dimension",
    "DimensionKind",
    "DrawingDocument",
    "Evidence",
    "Finding",
    "GDTCharacteristic",
    "GeometricTolerance",
    "GeometryFeature",
    "GeometryKind",
    "MaterialCondition",
    "Point2D",
    "ProjectionMethod",
    "Severity",
    "Sheet",
    "SourceFormat",
    "SurfaceFinish",
    "TaskKind",
    "TitleBlock",
    "TitleBlockField",
    "Tolerance",
    "ToleranceKind",
    "Units",
    "View",
    "WeldSymbol",
]
